# StatefulSet 配置
appName: nux-deposit-tracker
namespace: default

# 是否启用 annotations
annotations:
  enabled: false

# 副本数量
replicaCount: 1

appcm:
  enabled: fasle

secretEnv:
  enabled: true
  secrets:
  - secretName: deposit-secrets

# 镜像配置
image:
  repository: 590184059249.dkr.ecr.us-west-2.amazonaws.com/nudex/test-nudex-deposit-tracker
  tag: 20250128
  pullPolicy: Always

# StatefulSet 更新策略
strategy:
  type: RollingUpdate  # 可选择 RollingUpdate 或 OnDelete

# 资源限制与请求
appResources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "2Gi"

# initContainers 配置
initContainers:
  enabled: false

# 其他环境变量配置
env:
  ENV_VAR_NAME: value

# 文件beat 配置
filebeat:
  enabled: true
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 7.10.1
    pullPolicy: Always
  configName: filebeat-config
  logstashHost: "output-logstash.default:5045"

filebeatResources:
  limits:
    cpu: "500m"
    memory: "200Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

# filebeat env
filebeat_env:
  SPRING_PROFILES_ACTIVE: test
  ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  LOGSTASH_HOSTS: "logstash:5044"
  KIBANA_HOST: "kibana:5601"

# Deployment Service
service:
  type: ClusterIP
  ports:
  - name: nux-tracker
    # nodePort: 35678 # 如果type为NodePort，可以指定nodePort
    port: 80
    targetPort: 8080
    protocol: TCP
    isMonitorPort: false

serviceMonitor:
  enabled: false
  namespace: monitor
  release: "nudex-testnet"
  config:
    path: /metricsxw
    port: http-metrics
    scheme: http
    interval: 10s

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - nudex-testnet
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - nux-deposit-tracker
      topologyKey: kubernetes.io/hostname

# PVC 配置
volumeClaimTemplates:
  sharePvc: enable # pod 共享目录
  enabled: false # pod 独享目录
  pvItems:
    - name: deposit-tracker
      accessModes: ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: gp3-storage-class
      volumeMode: Filesystem
      mountPath: /app/data
      namespace: default

secretProviderClass:
  enabled: true
  className: testnet-secrets-goat
  name: secrets-store-inline
  mountPath: /mnt/secrets-store

serviceAccount:
  enabled: true
  name: testnet3-secret

# Health Check, add or modify customized livenessProbe  & readinessProbe
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30