appName: nudex-voter
namespace: default

replicaCount: 1

annotations:
  enabled: false


image:
  repository: 590184059249.dkr.ecr.us-west-2.amazonaws.com/nudex/dev-nudex-voter
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: p2p
      port: 4001
      targetPort: 4001

persistence:
  size: 50Gi
  storageClass: "gp3"


strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1


envFromSecrets:

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: voter
          operator: In
          values:
          - nudex-voter-node1
hostNetwork: true


mountsecret:
  enable: false
  secretProviderClass: nudex-voter-secrets
  secretName: awscredentials

serviceAccount: 
  enable: false
  name: nudex-voter-secret

appResources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "2Gi"


livenessProbe:
  failureThreshold: 3
  tcpSocket:
    port: 4001
  initialDelaySeconds: 10
  timeoutSeconds: 10
  periodSeconds: 10
readinessProbe:
  failureThreshold: 3
  tcpSocket:
    port: 4001
  initialDelaySeconds: 10
  timeoutSeconds: 10
  periodSeconds: 10
env:
  ENV_VAR_NAME: "value"