appName: nudex-voter-node3
namespace: goat-network

replicaCount: 1

annotations:
  enabled: false


image:
  repository: 108782057122.dkr.ecr.us-east-2.amazonaws.com/nudex/main-nudex-voter-server
  tag: v20250307155753-1
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: p2p
      port: 4001
      targetPort: 4001

persistence:
  size: 50Gi
  storageClass: "gp3"


updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    partition: 0

envFromSecrets:
- SUBMITTER_PRIVATE_KEY

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: voter
          operator: In
          values:
          - nudex-voter-node3
hostNetwork: true


mountsecret:
  enable: true
  secretProviderClass: nudex-voter-secrets3
  secretName: awscredentials-voter3

serviceAccount: 
  enabled: true
  name: nudex-secret-mainnet

appResources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "2Gi"


livenessProbe:
  failureThreshold: 3
  tcpSocket:
    port: 4001
  initialDelaySeconds: 10
  timeoutSeconds: 10
  periodSeconds: 10
readinessProbe:
  failureThreshold: 3
  tcpSocket:
    port: 4001
  initialDelaySeconds: 10
  timeoutSeconds: 10
  periodSeconds: 10
env:
  ENV_VAR_NAME: "value3"