apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- if .Values.annotations.enabled }}
  annotations: 
  {{- with .Values.annotations }}
   {{- range $key, $value := . }}
    {{- if ne $key "enabled" }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
   {{- end }}
  {{- end }}
  {{- end  }}
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  namespace: {{.Values.namespace }}
spec:
  serviceName: {{ .Values.appName }}
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  updateStrategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity: 
            {{- toYaml .Values.affinity.nodeAffinity | nindent 10 }}
      volumes:
      - name: tss-config
        configMap:
          name: {{ .Values.tssname }}-configmap
      - name: config-volume
        configMap:
          name: {{ .Values.appName }}-configmap  
      {{- if .Values.mountsecret }}
      {{- if .Values.mountsecret.enable }}
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.mountsecret.secretProviderClass }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- $secretName := .Values.mountsecret.secretName -}}
            {{- range .Values.envFromSecrets }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ . }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              echo "Waiting for tss-node on port 8180"
              until nc -z localhost 8180; do
                echo "Still waiting for tss-node on port 8180"
                sleep 10
              done
              echo "tss-node is ready. Starting nudex-voter"
              exec /app/nudex-voter -c /app/config.yaml
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: data
              mountPath: /app/db
          {{- if .Values.useSecretsStore }}
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.appResources.limits.cpu }}
              memory: {{ .Values.appResources.limits.memory }}
            requests:
              cpu: {{ .Values.appResources.requests.cpu }}
              memory: {{ .Values.appResources.requests.memory }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12}}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12}}


        - name: {{ .Values.tssname }}
          image: "{{ .Values.tssimage.repository }}:{{ .Values.tssimage.tag }}"
          imagePullPolicy: {{ .Values.tssimage.pullPolicy }}
          env:
            {{- $secretName := .Values.mountsecret.secretName -}}
            {{- range .Values.tssenvFromSecrets }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ . }}
            {{- end }}
          ports:
            {{- range .Values.service.tssports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: data-tss
              mountPath: /app/data
            - name: tss-config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources:
            {{- toYaml .Values.tssresources | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.tssreadinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.tsslivenessProbe | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
    - metadata:
        name: data-tss
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.tsssize }}