apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Values.nodeSelector.app }}
        podAntiAffinity: {{ toYaml .Values.affinity.podAntiAffinity | nindent 8 }}
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.envFromSecrets }}
          envFrom:
          - secretRef:
            name: {{ .Values.envFromSecrets }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: logs
              mountPath: /app/logs/{{ .Values.app.name }}
          resources:
            limits:
              cpu: {{ .Values.appResources.limits.cpu }}
              memory: {{ .Values.appResources.limits.memory }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.appLivenessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.appLivenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.appLivenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.appLivenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.appReadinessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.appReadinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.appReadinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.appReadinessProbe.periodSeconds }}
        - name: filebeat
          image: "{{ .Values.filebeat.image.repository }}:{{ .Values.filebeat.image.tag }}"
          imagePullPolicy: {{ .Values.filebeat.image.pullPolicy }}
          env:
            - name: APP_NAME
              value: "{{ .Values.app.name }}"
            - name: ELASTICSEARCH_HOSTS
              value: "{{ .Values.filebeat_env.ELASTICSEARCH_HOSTS }}"
            - name: LOGSTASH_HOSTS
              value: "{{ .Values.filebeat_env.LOGSTASH_HOSTS }}"
            - name: KIBANA_HOST
              value: "{{ .Values.filebeat_env.KIBANA_HOST }}"
          volumeMounts:
            - name: logs
              mountPath: /app/logs/{{ .Values.app.name }}
            - name: {{ .Values.filebeat.configName | default "filebeat-config" }}
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
          resources:
            limits:
              cpu: {{ .Values.filebeatResources.limits.cpu }}
              memory: {{ .Values.filebeatResources.limits.memory }}
      volumes:
        - emptyDir: {}
          name: logs
        - name: config
          configMap:
            name: filebeat-config
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}