apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.filebeat.configName }}
  namespace: {{.Values.namespace }}
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      processors:
      paths:
        - "{{ .Values.appLog.path }}/*.log"
      fields: 
        app_name: {{ .Values.appName }}
        namespaces: default
      close_inactive: 1m
      close_timeout: 3h
      clean_inactive: 72h
      ignore_older: 70h
      multiline.pattern: ^20[0-9]{2}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}
      multiline.negate: true
      multiline.match: after
      multiline.timeout: 50ms
      multiline.max_lines: 100
      exclude_files: ['debug']
    output.logstash: 
      hosts: ["output-logstash.default:5045"]