{{- if .Values.envFromSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envFromSecrets.secret_name }}
  namespace: {{ .Values.envFromSecrets.namespace }}
data:
  {{- range .Values.envFromSecrets.secrets }}
  {{ .name }}: {{ .key | b64enc }}
  {{- end }}
{{- end }}