apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    {{- range .Values.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- if eq .Values.serviceType "NodePort" }}
  nodePort: {{ .Values.nodePort }}
  {{- end }}
  {{- if eq .Values.serviceType "LoadBalancer" }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}
  {{- if .Values.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.externalTrafficPolicy }}
  {{- end }}
