apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.appName }}
      # {{- if eq .Values.service.type "NodePort" }}
      # nodePort: {{ .Values.service.nodePort }}
      # {{- end }}
      # {{- if eq .Values.service.type "LoadBalancer" }}
      # loadBalancerIP: {{ .Values.service.loadBalancerIP }}
      # {{- end }}