# Deployment Name
appName: alex-nux-test
namespace: alex-test

# Deployment Replicas
replicaCount: 2

# Deployment image
image:
  repository: 590184059249.dkr.ecr.us-east-2.amazonaws.com/nudex/nudex-server
  tag: nux-gateway-http-latest
  pullPolicy: Always

# Deployment Resources
appResources:
  limits:
    cpu: "1"
    memory: "2Gi"

# Deployment Health Check
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
# path: /health
# initialDelaySeconds: 30
# timeoutSeconds: 10
# periodSeconds: 30

# filebeat config default
filebeat:
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 7.10.1
    pullPolicy: Always
  configName: "filebeat-config"
  logstashHost: "output-logstash.default:5045"

filebeatResources:
  limits:
    cpu: "500m"
    memory: "200Mi"

# Deployment Service
service:
  ports:
  - name: alex-nux-test
    type: ClusterIP
    # nodePort: 35678 # 如果type为NodePort，可以指定nodePort
    port: 80
    targetPort: 8080
    protocol: TCP
    isMonitorPort: false
    # - name: https
    #   port: 443
    #   targetPort: 8443
    #   protocol: TCP
    # - name: grpc
    #   port: 50051
    #   targetPort: 50051
    #   protocol: TCP
  - name: testmonitor 
    port: 9090
    targetPort: 9090
    protocol: TCP
    isMonitorPort: true

# Deployment env
env:
  ENV_VAR_NAME: value
  SPRING_PROFILES_ACTIVE: test
  # JAVA_HEAP_OPTS: -Xmx2048M -Xms1024M -XX:MaxDirectMemorySize=128M
  # JAVA_OPTS: -Dspring.profiles.active=default

envFromSecrets:
  enabled: false
  # secrets:
  #   - name: secret-name
  #     key: secret-key

# filebeat env
filebeat_env:
  SPRING_PROFILES_ACTIVE: test
  ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  LOGSTASH_HOSTS: "logstash:5044"
  KIBANA_HOST: "kibana:5601"

nodeSelector:
  app: nudex-testnet

imagePullSecrets:
  - name: ecr-secret

serviceMonitor:
  enabled: true
  namespace: monitor
  release: "nudex-testnet"
  config:
    path: /metricsxw
    port: http-metrics
    scheme: http
    interval: 10s

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - alex-nudex-devnet
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - alex-nux-gateway-http
      topologyKey: kubernetes.io/hostname

