# Deployment Name
appName: appname
namespace: alex-test

annotations:
  enabled: false

# Deployment Replicas
replicaCount: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

# Deployment Resources
appResources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "200m"
    memory: "512Mi"

# Deployment Health Check, add or modify customized livenessProbe  & readinessProbe
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
# path: /health
# initialDelaySeconds: 30
# timeoutSeconds: 10
# periodSeconds: 30

# filebeat config default
filebeat:
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 7.10.1
    pullPolicy: Always
  configName: "filebeat-config"
  logstashHost: "output-logstash.default:5045"

filebeatResources:
  limits:
    cpu: "500m"
    memory: "200Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

# Deployment Service
service:
  type: ClusterIP
  ports:
  - name: appname
    # nodePort: 35678 # 如果type为NodePort，可以指定nodePort
    port: 80
    targetPort: 8080
    protocol: TCP
    isMonitorPort: false
  # - name: https
  #   port: 443
  #   targetPort: 8443
  #   protocol: TCP
  # - name: grpc
  #   port: 50051
  #   targetPort: 50051
  #   protocol: TCP
  # - name: monitorname 
  #   port: 9090
  #   targetPort: 9090
  #   protocol: TCP
  #   isMonitorPort: true

# Deployment env
env:
  ENV_VAR_NAME: value

envFromSecrets:
  enabled: false
  # secrets:
  #   - name: secret-name
  #     key: secret-key

# filebeat env
filebeat_env:
  SPRING_PROFILES_ACTIVE: test
  ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  LOGSTASH_HOSTS: "logstash:5044"
  KIBANA_HOST: "kibana:5601"

imagePullSecrets:
  - name: ecr-secret

serviceMonitor:
  enabled: false
  namespace: monitor
  release: "nudex-testnet"
  config:
    path: /metricsxw
    port: http-metrics
    scheme: http
    interval: 10s

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - tagname
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - tagname
      topologyKey: kubernetes.io/hostname