appName: nux-gateway-http

replicaCount: 2

image:
  repository: 590184059249.dkr.ecr.us-east-2.amazonaws.com/nudex/nudex-server
  tag: nux-gateway-http-latest
  pullPolicy: Always

filebeat:
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 7.10.1
    pullPolicy: Always
  configName: "filebeat-config"
  logstashHost: "output-logstash.default:5045"

appResources:
  limits:
    cpu: "1"
    memory: "2Gi"

LivenessProbe:
  path: /health
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30

ReadinessProbe:
  path: /health
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30

filebeatResources:
  limits:
    cpu: "500m"
    memory: "200Mi"

service:
  type: ClusterIP
  nodePort: nil
  loadBalancerIP: nil
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    # - name: https
    #   port: 443
    #   targetPort: 8443
    #   protocol: TCP
    # - name: grpc
    #   port: 50051
    #   targetPort: 50051
    #   protocol: TCP

env:
  ENV_VAR_NAME: value
  SPRING_PROFILES_ACTIVE: test
  # JAVA_HEAP_OPTS: -Xmx2048M -Xms1024M -XX:MaxDirectMemorySize=128M
  # JAVA_OPTS: -Dspring.profiles.active=default

envFromSecrets:
  enabled: false

filebeat_env:
  SPRING_PROFILES_ACTIVE: test
  ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  LOGSTASH_HOSTS: "logstash:5044"
  KIBANA_HOST: "kibana:5601"

nodeSelector:
  app: nudex-testnet

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - nux-gateway-http
        topologyKey: kubernetes.io/hostname

imagePullSecrets:
  - name: ecr-secret

serviceMonitor:
  enabled: false