# Deployment Name
appName: nux-deposit-tracker
namespace: default
labels:
  app: nux-deposit-tracker

appLog:
  path: /app/logs/nip-indexer

# Deployment Replicas
replicaCount: 1

#add annotations
annotations:
  enabled: false

#add configmap
appcm:
  enabled: false
  # name: nux-deposit-tracker-cm
  # namespace: default
  # mountPath: /app/config

# initContainers 配置
initContainers:
  enabled: false

strategy:
  type: Recreate

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - nudex-devnet
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - nux-deposit-tracker
      topologyKey: kubernetes.io/hostname

# Deployment env
env:
  ENV_VAR_NAME: value
  SPRING_PROFILES_ACTIVE: dev
  ENV_FILE: .dev.env

secretEnv:
  enabled: true
  secretKeyRef:
  - secretName: deposit-secrets
    key: test
  - secretName: deposit-secrets
    key: test

# PVC 配置
volumeClaimTemplates:
  sharePvc: true # pod 共享目录
  pvItems:
    - name: deposit-tracker
      accessModes: ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: gp3
      volumeMode: Filesystem
      mountPath: /app/data
      namespace: default

# Deployment image
image:
  repository: 590184059249.dkr.ecr.us-west-2.amazonaws.com/nudex/dev-nudex-deposit-tracker
  tag: latest
  pullPolicy: Always

# Deployment Resources
appResources:
  limits:
    cpu: "4"
    memory: "8Gi"
  requests:
    cpu: "1"
    memory: "2Gi"

# Deployment Health Check
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  periodSeconds: 30
readinessProbe:
  failureThreshold: 3
  successThreshold: 1
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30

# Deployment Service
service:
  ports:
  - name: nux-tracker
    type: ClusterIP
    # nodePort: 35678 # 如果type为NodePort，可以指定nodePort
    port: 80
    targetPort: 8080
    protocol: TCP
    isMonitorPort: false
  # - name: healthcheck
  #   type: ClusterIP
  #   port: 8080
  #   targetPort: 8080
  #   protocol: TCP
  #   isMonitorPort: false

#default  image secret
imagePullSecrets:
  - name: new-ecr-secret

# filebeat config default
filebeat:
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 7.10.1
    pullPolicy: Always
  configName: "tracker-fb-cm"
  logstashHost: "output-logstash.default:5045"

filebeatResources:
  limits:
    cpu: "500m"
    memory: "200Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

# filebeat env
filebeat_env:
  ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  LOGSTASH_HOSTS: "logstash:5044"
  KIBANA_HOST: "kibana:5601"

serviceMonitor:
  enabled: false
  namespace: monitor
  release: "nudex-testnet"
  config:
    path: /metricsxw
    port: http-metrics
    scheme: http
    interval: 10s
