# Deployment Name
appName: nux-gateway-ws
namespace: exchange
labels:
  app: nux-gateway-ws

appLog:
  path: /app/logs/

annotations:
  enabled: false

secretProviderClass:
  enabled: false

serviceAccount:
  enabled: false

appcm:
  enabled: false

volumeClaimTemplates:
  sharePvc: false # pod 共享目录
  enabled: false # pod 独享目录

initContainers:
  enabled: false

secretEnv:
  enabled: true
  secrets:
  -  secretName: dev-nacos
# Deployment Replicas
replicaCount: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - nudex-devnet
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - nux-gateway-ws
      topologyKey: kubernetes.io/hostname

# Deployment env
env:
  ENV_VAR_NAME: value
  SPRING_PROFILES_ACTIVE: dev
  JAVA_OTEL_ENV: ""
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus,health,info,metrics
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  DEFAULT_JAVA_OPTS: " \
    -Dfile.encoding=UTF-8 \
    -XX:+UseZGC \
    -Drocketmq.client.logUseSlf4j=true \
    -Dcom.alibaba.nacos.naming.cache.dir=/tmp/nacos/naming \
    -DJM.SNAPSHOT.PATH=/tmp/nacos/config \
    -Dspring.profiles.active=dev \
    -Dmanagement.server.port=10000 \
    -DAPP_NAME=$(POD_NAME)"
  JAVA_HEAP_OPTS: "-Xmx4G -Xms2G"

envFromSecrets:
  enabled: false
  # secrets:
  #   - name: secret-name
  #     key: secret-key

# Deployment image
image:
  repository: 590184059249.dkr.ecr.us-west-2.amazonaws.com/nudex/dev-gateway-ws
  tag: latest
  pullPolicy: Always

# Deployment Resources
appResources:
  limits:
    cpu: "500m"
    memory: "5Gi"
  requests:
    cpu: "100m"
    memory: "500Mi"

# Deployment Health Check
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /actuator/health
    port: 10000
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  periodSeconds: 30
readinessProbe:
  failureThreshold: 3
  successThreshold: 1
  httpGet:
    path: /actuator/health
    port: 10000
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30

# Deployment Service
service:
  ports:
  - name: gateway-ws
    type: ClusterIP
    # nodePort: 35678 # 如果type为NodePort，可以指定nodePort
    port: 9081
    targetPort: 9081
    protocol: TCP
    isMonitorPort: false
  - name: public
    type: ClusterIP
    port: 8090
    targetPort: 8090
    protocol: TCP
    isMonitorPort: false
  - name: private
    type: ClusterIP
    port: 8091
    targetPort: 8091
    protocol: TCP
    isMonitorPort: false
  - name: management
    port: 10000
    targetPort: 10000
    protocol: TCP
    isMonitorPort: true
    path: /actuator/prometheus
    scheme: http
    interval: 10s
#default  image secret
imagePullSecrets:
  enabled: false

# filebeat config default
filebeat:
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 7.10.1
    pullPolicy: Always
  configName: " gateway-ws"
  logstashHost: "output-logstash.default:5045"

filebeatResources:
  limits:
    cpu: "500m"
    memory: "200Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

# filebeat env
filebeat_env:
  SPRING_PROFILES_ACTIVE: test
  ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  LOGSTASH_HOSTS: "logstash:5044"
  KIBANA_HOST: "kibana:5601"

serviceMonitor:
  enabled: false
  namespace: monitor
  release: "devnet"
  jobLabel: "nudex-devnet"