# Deployment Name
appName: appname
namespace: alex-test

# Deployment Replicas
replicaCount: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

# Deployment image
image:
  repository: 590184059249.dkr.ecr.us-east-2.amazonaws.com/nudex/nudex-server
  tag: nux-gateway-http-latest
  pullPolicy: Always

# Deployment Resources
appResources:
  limits:
    cpu: "1"
    memory: "2Gi"

# Deployment run command
customArgs:
  enabled: false
  args:
  - "- -javaagent:/app/opentelemetry-javaagent.jar"
  - "- -Dotel.traces.exporter=otlp"
  - "- -Dotel.metrics.exporter=otlp"
  - "- -Dotel.exporter.otlp.endpoint=http://otel-collector-collector.opentelemetry-operator-system:4317"
  - "- -Dotel.resource.attributes=service.name=nux-demo-server,service.version=1.0"
  - "- -XX:+UseZGC"
  - "- -XX:ParallelGCThreads=2"
  - "- -Xms256m"
  - "- -Xmx512m"
  - "- -XX:+UseStringDeduplication"
  - "- -Dfile.encoding=UTF-8"
  - "- -jar"
  - "- ./application.jar"
  command:
  - "- java"

# Deployment Health Check, add or modify customized livenessProbe  &readinessProbe
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
# path: /health
# initialDelaySeconds: 30
# timeoutSeconds: 10
# periodSeconds: 30

# filebeat config default
filebeat:
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 7.10.1
    pullPolicy: Always
  configName: "filebeat-config"
  logstashHost: "output-logstash.default:5045"

filebeatResources:
  limits:
    cpu: "500m"
    memory: "200Mi"

# Deployment Service
service:
  ports:
  - name: appname
    type: ClusterIP
    # nodePort: 35678 # 如果type为NodePort，可以指定nodePort
    port: 80
    targetPort: 8080
    protocol: TCP
    isMonitorPort: false
    # - name: https
    #   port: 443
    #   targetPort: 8443
    #   protocol: TCP
    # - name: grpc
    #   port: 50051
    #   targetPort: 50051
    #   protocol: TCP
  - name: monitorname 
    port: 9090
    targetPort: 9090
    protocol: TCP
    isMonitorPort: true

# Deployment env
env:
  ENV_VAR_NAME: value
  SPRING_PROFILES_ACTIVE: test

envFromSecrets:
  enabled: false
  # secrets:
  #   - name: secret-name
  #     key: secret-key

# filebeat env
filebeat_env:
  SPRING_PROFILES_ACTIVE: test
  ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  LOGSTASH_HOSTS: "logstash:5044"
  KIBANA_HOST: "kibana:5601"

nodeSelector:
  app: node-tag

imagePullSecrets:
  - name: ecr-secret

serviceMonitor:
  enabled: false
  namespace: monitor
  release: "nudex-testnet"
  config:
    path: /metricsxw
    port: http-metrics
    scheme: http
    interval: 10s

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - tagname
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - tagname
      topologyKey: kubernetes.io/hostname

