replicaCount: 2

image:
  repository: 590184059249.dkr.ecr.us-east-2.amazonaws.com/nudex/nudex-server
  tag: nux-gateway-http-latest
  pullPolicy: Always

filebeat:
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 7.10.1
    pullPolicy: Always

resources:
  limits:
    cpu: "1"
    memory: "2Gi"

filebeatResources:
  limits:
    cpu: "500m"
    memory: "200Mi"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  SPRING_PROFILES_ACTIVE: test
  ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  LOGSTASH_HOSTS: "logstash:5044"
  KIBANA_HOST: "kibana:5601"

nodeSelector:
  app: nudex-testnet

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - nux-gateway-http
        topologyKey: kubernetes.io/hostname

imagePullSecrets:
  - name: ecr-secret