{{- if .Values.volumeClaimTemplates.sharePvc }}
{{- range .Values.volumeClaimTemplates.pvItems }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .namespace }}
  name: {{ .name }}
spec:
  accessModes: [{{ .accessModes |quote }}]  # EFS 支持 ReadWriteMany 模式
  resources:
    requests:
      storage: {{ .resources.requests.storage }}
  storageClassName: {{ .storageClassName }} # 对应的 StorageClass
  volumeMode: {{ .volumeMode }}  # EFS 是文件系统类型
  {{- end }}
{{- end }}
