{{- if .Values.serviceMonitor.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  endpoints: 
    {{- range .Values.service.ports }}
    {{- if .isMonitorPort  }}
    - port: {{ .name }}
      path: {{ .path }}
      scheme: {{ .scheme }}
      interval: {{ .interval }}
    {{- end }}
    {{- end }}
  jobLabel: {{ .Values.serviceMonitor.release }}
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
  selector: 
    matchLabels:
      app: {{ .Values.appName }}
{{- end}}